name: Deploy to AWS EC2

on:
  push:
    branches:
      - master  # Trigger this workflow on pushes to the master branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # This will run on the latest Ubuntu runner

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Run tests
    - name: Run tests
      run: |
        python manage.py test

    # Set up SSH and deploy to EC2
    - name: Set up SSH and deploy to EC2
      uses: shivammathur/setup-ssh@v1
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}
        remote-username: ubuntu
        remote-host: ${{ secrets.EC2_HOST }}
        script: |
          # Navigate to the app directory or clone if not exists
          if [ ! -d "/app" ]; then
            git clone https://github.com/rahulkum99/salon4me.git /app
          else
            cd /app && git pull origin main
          fi

          # Build and run Docker container
          cd /app
          docker build -t django-app .
          docker stop django-container || true
          docker rm django-container || true
          docker run -d --name django-container -p 8000:8000 django-app

    # Optional: Notify success
    - name: Notify Deployment
      run: echo "Deployment to EC2 instance successful!"
